type: default
db:
  DB_TYPE: mysql
  DB_HOST: 127.0.0.1
  DB_PORT: 3306
  DB_DATABASE: testdb
  DB_USERNAME: root
  DB_PASSWORD: '123456'
  DB_SYNC: true
log:
  PATH: logs
  ON: false
  LEVEL: info
jwt:
  SECRET: CX4nojjoJpuosqgezsUWuXTWFJttjS3CPJsPWsmPk57CU6M57S11YeoVeEnWruTd
